scripts

diff --git a/bin/check-conductor b/bin/check-conductor
--- a/bin/check-conductor
+++ b/bin/check-conductor
@@ -1,56 +1,31 @@
 #!/usr/bin/env bash
 # doc: Kontroluje CONDUCTOR logy pro vybraný mart a engine
 
-# colors
-MM_ERR="\e[31mERR\e[0m"
-MM_TRY="\033[33mTRY\033[0m"
-MM_OK="\033[34mOK\033[0m "
+[ "$(type -t include)" != 'function' ]&&{ include(){ { [ -z "$_IR" ]&&_IR="$PWD"&&cd "$(dirname "${BASH_SOURCE[0]}")"&&include "$1"&&cd "$_IR"&&unset _IR;}||{ local d="$PWD"&&cd "$(dirname "$PWD/$1")"&&. "$(basename "$1")"&&cd "$d";}||{ echo "Include failed $PWD->$1"&&exit 1;};};}
+include "lib/user_io.sh"
+include "lib/die.sh"
 
 
 # produkce a mount point
-echo -e "$MM_TRY: checking mount point"
-
 MNT_FILE="$HOME/dotfiles/bin/net-mount-points/virt_node@prod"
-source $MNT_FILE
+source "$MNT_FILE" || fDie "Failed to source: $MNT_FILE"
 findmnt $_MNT_ >/dev/null 2>&1
-if [ $? -ne 0 ]; then
-    echo -e "$MM_ERR: not mounted: $_MNT_"
-    exit 1
-fi
-echo -e "$MM_OK: mounted"
+[ $? -ne 0 ] && fDie "not mounted: $_MNT_"
+
 
 # vyber engine
 PMROOTDIR=$(echo "PMRootDir_ASG
-PMRootDir_A29
-" | fzf)
-
-if [[ -z "$PMROOTDIR" ]] ; then
-    echo -e "$MM_ERR: Empty selection"
-    exit 1    
-else
-    echo -e "$MM_OK: Checking $PMROOTDIR"
-fi
-
+PMRootDir_A29" | fzf)
+[[ -z "$PMROOTDIR" ]] && fDie "Empty selection: PMROOTDIR='$PMROOTDIR'"
 PMWORKFLOWLOGDIR=$(echo $PMROOTDIR | sed s/PMRootDir/PMWorkflowLogDir/)
 
 # vyber jeden mart
 DEF_MASK="$_MNT_/EDW/$PMROOTDIR/py_mart_def/*.json"
-echo -e "$MM_TRY: get list of def files"
-MART=$(ls -1 $DEF_MASK | cut -d '/' -f 7  | sed  s/.json// | fzf)
-echo $MART
-
-# pokud nemáš mart, nic nedělej
-if [[ -z "$MART" ]] ; then
-    echo -e "$MM_ERR: Empty selection"
-    exit 1    
-else
-    echo -e "$MM_OK: Checking $MART"
-fi
+MART=$(ls -1 $DEF_MASK | cut -d '/' -f 7  | sed  s/.json// | fzf --prompt "Vyber datamart")
+[[ -z "$MART" ]] && fDie "Empty selection"
 
 # pokud máš mart, projeď jeho historii
 LOG_FILE=$(find "$_MNT_/EDW/$PMWORKFLOWLOGDIR" -maxdepth 1 -type f -name "*CONDUCTOR*" | head -n 1 )
-echo -e "$MM_TRY: checking: $LOG_FILE"
+[[ -z "$LOG_FILE" ]] && fDie "Nenašel jsem ani jeden log soubor jobu CONDUCTOR"
 
-cat $LOG_FILE | grep $MART | grep -E 'next_run_dttm|missing|_restart_mart_starter_job|schedule'
-
-#  grep "critical" | grep $MART | tail
+cat $LOG_FILE | grep $MART | grep -E 'next_run_dttm|missing|_restart_mart_starter_job|schedule' | batcat
diff --git a/bin/fcd-feature-script b/bin/fcd-feature-script
--- a/bin/fcd-feature-script
+++ b/bin/fcd-feature-script
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 # doc: Rychlé přepínání do feature adresářů pomocí fzf
+[ "$(type -t include)" != 'function' ]&&{ include(){ { [ -z "$_IR" ]&&_IR="$PWD"&&cd "$(dirname "${BASH_SOURCE[0]}")"&&include "$1"&&cd "$_IR"&&unset _IR;}||{ local d="$PWD"&&cd "$(dirname "$PWD/$1")"&&. "$(basename "$1")"&&cd "$d";}||{ echo "Include failed $PWD->$1"&&exit 1;};};}
+include "lib/user_io.sh"
+include "lib/die.sh"
+
 FEAT_DIR="$HOME/o2-feature"
 SELECTED_DIR=$(find $HOME/o2-feature -maxdepth 1 -type d | grep -vE "o2-feature$" | fzf)
+[[ ! -n "$SELECTED_DIR" ]] && fDie "No directory selected."
+SELECTED_DIR="${SELECTED_DIR%%#*}" # get everything before the pound (strip comments)
+SELECTED_DIR=$(echo "$SELECTED_DIR" | sed 's/[[:space:]]*$//') # strip spaces at the end
+cd "$SELECTED_DIR"
+printSuccess "cd $SELECTED_DIR"
 
-# Check if a directory was selected
-if [[ ! -n "$SELECTED_DIR" ]]; then
-  echo "No directory selected."
-else
-    SELECTED_DIR="${SELECTED_DIR%%#*}" # get everything before the pound (strip comments)
-    SELECTED_DIR=$(echo "$SELECTED_DIR" | sed 's/[[:space:]]*$//') # strip spaces at the end
-    echo "go to $SELECTED_DIR"
-    cd "$SELECTED_DIR"
-fi
diff --git a/bin/fcd-script b/bin/fcd-script
--- a/bin/fcd-script
+++ b/bin/fcd-script
@@ -1,26 +1,27 @@
 #!/usr/bin/env bash
 # doc: Přepínání mezi adresáři a URL z bookmarks pomocí fzf
 
+[ "$(type -t include)" != 'function' ]&&{ include(){ { [ -z "$_IR" ]&&_IR="$PWD"&&cd "$(dirname "${BASH_SOURCE[0]}")"&&include "$1"&&cd "$_IR"&&unset _IR;}||{ local d="$PWD"&&cd "$(dirname "$PWD/$1")"&&. "$(basename "$1")"&&cd "$d";}||{ echo "Include failed $PWD->$1"&&exit 1;};};}
+include "lib/user_io.sh"
+include "lib/die.sh"
+
 BOOKMARKS_FILE=~/bookmarks
 SELECTED_DIR=$(cat "$BOOKMARKS_FILE" | fzf)
 BROWSER=/usr/bin/google-chrome-stable
 
-# Check if a directory was selected
-if [[ ! -n "$SELECTED_DIR" ]]; then
-  echo "No directory selected."
-else
-    # check if it starts with a slash
-    if [[ $SELECTED_DIR == /* ]]; then        
-        SELECTED_DIR="${SELECTED_DIR%%#*}" # get everything before the pound (strip comments)
-        SELECTED_DIR=$(echo "$SELECTED_DIR" | sed 's/[[:space:]]*$//') # strip spaces at the end
-        echo "go to $SELECTED_DIR"
-        cd "$SELECTED_DIR"
-    fi
+[[ ! -n "$SELECTED_DIR" ]] && fDie "No directory selected."
 
-    # check if it starts wityh a slash
-    if [[ $SELECTED_DIR == http* ]]; then
-        echo "run chrome $SELECTED_DIR"
-        $BROWSER "$SELECTED_DIR"
-
-    fi
+# check if it starts with a slash
+if [[ $SELECTED_DIR == /* ]]; then        
+    SELECTED_DIR="${SELECTED_DIR%%#*}" # get everything before the pound (strip comments)
+    SELECTED_DIR=$(echo "$SELECTED_DIR" | sed 's/[[:space:]]*$//') # strip spaces at the end        
+    cd "$SELECTED_DIR"
+    printSuccess "cd $SELECTED_DIR"
 fi
+
+# check if it starts wityh a slash
+if [[ $SELECTED_DIR == http* ]]; then    
+    $BROWSER "$SELECTED_DIR"
+
+fi
+
diff --git a/bin/is-valid-json b/bin/is-valid-json
--- a/bin/is-valid-json
+++ b/bin/is-valid-json
@@ -1,27 +1,20 @@
 #!/usr/bin/env bash
 # doc: Validuje JSON soubor pomocí jq a vrací exit kódy
 
-# colors
-ERR="\e[31mERR\e[0m"
-TRY="\033[33mTRY\033[0m"
-OK="\033[34mOK\033[0m "
+[ "$(type -t include)" != 'function' ]&&{ include(){ { [ -z "$_IR" ]&&_IR="$PWD"&&cd "$(dirname "${BASH_SOURCE[0]}")"&&include "$1"&&cd "$_IR"&&unset _IR;}||{ local d="$PWD"&&cd "$(dirname "$PWD/$1")"&&. "$(basename "$1")"&&cd "$d";}||{ echo "Include failed $PWD->$1"&&exit 1;};};}
+include "lib/user_io.sh"
+include "lib/die.sh"
 
 
-if [ $# -ne 1 ]; then
-  echo "Usage: $0 <filename>"
-  exit 1
-fi
-
-
+[ $# -ne 1 ] && fDie "Usage: $0 <filename>"
 
 if ! command -v jq >/dev/null 2>&1; then
-  echo "Error: 'jq' is not installed."
+  fDie "Error: 'jq' is not installed."
   exit 2
 fi
 
 if jq empty "$1" >/dev/null 2>&1; then
-  echo -e "$OK json in $1 is valid"
+  printSuccess "valid json: $1"
 else
-  echo -e "$ERR Invalid JSON in $1"
-  exit 3
+  fDie "INVALID JSON: $1"
 fi
diff --git a/bin/netmount b/bin/netmount
--- a/bin/netmount
+++ b/bin/netmount
@@ -1,16 +1,11 @@
 #!/usr/bin/env bash
 # doc: Připojí VPN a namountuje síťové disky s možností git fetch
-source $HOME/bin/basic-func.sh
+[ "$(type -t include)" != 'function' ]&&{ include(){ { [ -z "$_IR" ]&&_IR="$PWD"&&cd "$(dirname "${BASH_SOURCE[0]}")"&&include "$1"&&cd "$_IR"&&unset _IR;}||{ local d="$PWD"&&cd "$(dirname "$PWD/$1")"&&. "$(basename "$1")"&&cd "$d";}||{ echo "Include failed $PWD->$1"&&exit 1;};};}
+include "lib/user_io.sh"
+include "lib/die.sh"
 
 # tohle sice nesouvisí se sítí ale fakt mě to štve
 amixer -c 1 set Headphone unmute
-
-if [[ $? -eq 0 ]]; then
-  flog "Sourcing succeeded"
-else
-  echo "Sourcing failed"
-  exit 1
-fi
 
 mount_points_def_dir=$HOME/bin/net-mount-points
 domain_passfile=$HOME/Vaults/o2/domain-password.txt
@@ -23,12 +18,12 @@ mount
 jenom vpn" | fzf)
 
 # sanity check and cryfs
-[[ -d "$mount_points_def_dir" ]] || fdie "Directory does not exist: $mount_points_def_dir"
+[[ -d "$mount_points_def_dir" ]] || fDie "Directory does not exist: $mount_points_def_dir"
 if [[ ! -f "$domain_passfile" ]]; then
-    flog "try to read: $domain_passfile" info
-    cryfs $HOME/.local/share/plasma-vault/o2.enc $HOME/Vaults/o2/ || fdie "cryfs failed"
+    printInfo "try to read: $domain_passfile"
+    cryfs $HOME/.local/share/plasma-vault/o2.enc $HOME/Vaults/o2/ || fDie "cryfs failed"
 fi
-[[ -f "$domain_passfile" ]] || fdie "File does not exist: $domain_passfile"
+[[ -f "$domain_passfile" ]] || fDie "File does not exist: $domain_passfile"
 
 
 # načti secrets a další
@@ -36,8 +31,8 @@ var_me=$(whoami)
 var_uid=$(id -u $var_me)
 var_gid=$(id -g $var_me)
 var_pass=$(<$HOME/Vaults/o2/domain-password.txt)
-[[ -z $var_pass ]] && fdie "failed to read domain password from $domain_passfile"
-flog "secrets read sucessfully" info
+[[ -z $var_pass ]] && fDie "failed to read domain password from $domain_passfile"
+printInfo "secrets read sucessfully"
 
 # test napojení na VPN
 is_on_vpn=$(nmcli connection show --active | grep extvpn.o2.cz)
@@ -46,13 +41,13 @@ is_on_vpn=$(nmcli connection show --active | grep extvpn.o2.cz)
 if [[ -z "$is_on_vpn" ]]; then
     # CISCO # if [[ ! -d "$HOME/.cisco" ]]; then
     # CISCO #     flog "copy certificates: cp -r $src_cisco_path $HOME" warning
-    # CISCO #     cp -r "$src_cisco_path" $HOME || fdie "copy failed!"
-    # CISCO #     [[ -d "$HOME/.cisco" ]] || fdie "folder $HOME/.cisco does not exist!"
+    # CISCO #     cp -r "$src_cisco_path" $HOME || fDie "copy failed!"
+    # CISCO #     [[ -d "$HOME/.cisco" ]] || fDie "folder $HOME/.cisco does not exist!"
     # CISCO # fi
 
-	flog "connecting to VPN" warning
-	nmcli connection up extvpn.o2.cz 1>/dev/null 2>&1 || fdie "failed to connect"
-    # CISCO # # lepší přes GUI $vpn_client connect extvpn.o2.cz || fdie "failed to connect"
+	printInfo "connecting to VPN"
+	nmcli connection up extvpn.o2.cz 1>/dev/null 2>&1 || fDie "failed to connect"
+    # CISCO # # lepší přes GUI $vpn_client connect extvpn.o2.cz || fDie "failed to connect"
     # CISCO # $vpn_client_ui >/dev/null 2>&1 & 
     
     # infinite loop
@@ -65,7 +60,7 @@ if [[ -z "$is_on_vpn" ]]; then
         # COSCO # fi
         is_on_vpn=$(nmcli connection show --active | grep extvpn.o2.cz)
         if [[ -z "$is_on_vpn" ]]; then
-            flog "waiting on VPN to connect..." warning
+            printInfo "waiting on VPN to connect..."
             sleep 1
         else
             break
@@ -73,7 +68,7 @@ if [[ -z "$is_on_vpn" ]]; then
     done 
     [[ -f $HOME/Vaults/o2/after-connect.sh ]] && $HOME/Vaults/o2/after-connect.sh
 else
-    flog "VPN is already connected" info
+    printSuccess "VPN is already connected"
 fi
 
 $HOME/bin/set-proxy-on
@@ -83,15 +78,15 @@ $HOME/bin/set-proxy-on
 #if [ "${__MOUNT_DRIVES__^^}" = "Y" ]; then 
 if [[ "$what_to_do" =~ "mount" ]]; then
     for mount_point in "$mount_points_def_dir"/*; do
-        flog "read $mount_point" info
+        printInfo "read $mount_point"
         source $mount_point
 
         if [ -d "$_MNT_" ]; then
             findmnt $_MNT_ >/dev/null 2>&1
             if [ $? -eq 0 ]; then
-                flog "directory is already mounted: $_MNT_" warning
+                printWarning "directory is already mounted: $_MNT_"
             else
-                flog "mounting $_SRC_" info
+                printInfo "mounting $_SRC_" info
                 MM_OPTIONS="domain=TO2,username=X0548834,"
                 MM_OPTIONS+="password=$var_pass,"
                 MM_OPTIONS+="uid=$var_uid,"
@@ -101,7 +96,7 @@ if [[ "$what_to_do" =~ "mount" ]]; then
                 sudo mount -t cifs -o $MM_OPTIONS $_SRC_ $_MNT_
 
                 if [[ $? -gt 0 ]]; then
-                    flog "failed to mount $_SRC_" error
+                    printError "failed to mount $_SRC_"
                 fi
             fi
         fi
