sada korekcí skriptů

diff --git a/bin/dpl b/bin/dpl
--- a/bin/dpl
+++ b/bin/dpl
@@ -4,27 +4,6 @@
 MM_ERR="\e[31mERR\e[0m"
 MM_TRY="\033[33mTRY\033[0m"
 MM_OK="\033[34mOK\033[0m "
-
-#DEPLOY_DIR=/mnt/dev-virt-node/EDW_JHE
-
-DEPLOY_DIR=$(echo "/mnt/dev-virt-node/EDW_JHE
-/mnt/dev-virt-node/VODWH_JHE
-/home/jan/o2/BIDEV-MAIN_vodwh/src
-/home/jan/o2/BIDEV-MAIN_edw/SRC/e09
-/home/jan/o2/BIDEV-MAIN_edw/SRC/e29
-" | fzf --prompt="Select deploy directory: " --height=10 --border)
-
-if [[ -z "$DEPLOY_DIR" ]] ; then
-    echo -e "$MM_ERR: Empty selection"
-    exit 1    
-else
-    echo -e "$MM_OK: Deploy to $DEPLOY_DIR"
-fi
-
-
-CURRENT_DIR=`pwd`
-BACKUP_OF_CWD="$CURRENT_DIR"
-
 PROJECT_FILE="project.json"
 
 # Function to find a file in the current or parent directories
@@ -41,14 +20,70 @@ find_file_in_parents() {
     done
 
     echo -e "$MM_ERR: $target_file not found"
-    return 1  # Not found
+    exit 1  # Not found
 }
 
+
+
+# v jakém jsme adresáři?
+CURRENT_DIR=$(pwd)
+BACKUP_OF_CWD="$CURRENT_DIR"
 
 # najdi si projekt v aktuální nebo v nadřazené složce
 find_file_in_parents
 echo -e "$MM_OK: cd to $CURRENT_DIR"
 cd $CURRENT_DIR
+
+
+# na jaké prostředí budeme nasazovat skripty?
+DEPLOY_DIR=$(echo "/mnt/dev-virt-node/EDW_JHE
+/mnt/dev-virt-node/VODWH_JHE
+/home/jan/o2/BIDEV-MAIN_vodwh/src
+/home/jan/o2/BIDEV-MAIN_edw/mstr/SRC/e09
+/home/jan/o2/BIDEV-MAIN_edw/mstr/SRC/e29
+" | fzf --prompt="Select deploy directory: " --height=10 --border)
+
+if [[ -z "$DEPLOY_DIR" ]] ; then
+    echo -e "$MM_ERR: Empty selection"
+    exit 1    
+else
+    echo -e "$MM_OK: Deploy to $DEPLOY_DIR"
+fi
+
+# budeme nasazovat na Oracle?
+# pouze pokud cílová složka obsahuje mount (mnt)
+if [[ "$DEPLOY_DIR" == *"/mnt/"* ]] ; then
+    TO_DEPLOY=$(find . -type f | grep -i pdc | fzf --prompt "Select a PDC deployment script to run: " --header "Select a script to deploy:")
+    if [ ! -z "$TO_DEPLOY" ]; then
+        PDC=$(echo "PDC_X0548834" | fzf --prompt "Which PDC? " --header "Select a PDC to deploy to:")
+        if [ -z "$PDC" ]; then
+        echo "No PDC selected, exiting."
+        exit 0
+        fi
+        PASSWORD=x$PDC
+        TNSNAME=BIDEVELOP
+
+        KILL_SCRIPT_DIR=$HOME/bin/pdc-engines
+        KILL_ENGINE=$(ls $KILL_SCRIPT_DIR | fzf --prompt "Do you want to kill the engine? ESC to keep all intact " --header "Select an option:")
+        if [ ! -z "$KILL_ENGINE" ]; then
+        KILLSCRIPT=$KILL_SCRIPT_DIR/$KILL_ENGINE
+        echo "Killing engine with script: $KILLSCRIPT"
+        echo exit | sqlplus $PDC/$PASSWORD@$TNSNAME @$KILLSCRIPT
+        
+        if [ $? -ne 0 ]; then
+            echo "DEPLOYMENT FAILED"
+            exit 1
+            fi  
+        fi
+
+
+        echo exit | sqlplus $PDC/$PASSWORD@$TNSNAME @$TO_DEPLOY
+        if [ $? -ne 0 ]; then
+            echo "DEPLOYMENT FAILED"
+            exit 1
+        fi
+    fi
+fi
 
 
 # kontrola existence adresáře s definicemi
@@ -69,4 +104,9 @@ fi
 
 echo -e "$MM_OK: yes | cp -r $OUTPUT_DIR/* $DEPLOY_DIR"
 yes | cp -L -r $OUTPUT_DIR/* $DEPLOY_DIR
+
+
 cd $BACKUP_OF_CWD
+
+
+
