přepis na flog

diff --git a/bin/fmount b/bin/fmount
--- a/bin/fmount
+++ b/bin/fmount
@@ -1,64 +1,57 @@
 #!/bin/bash
-USERNAME="a1548834"
 
-LINUX_USERNAME=`whoami`
-ME_UID=`id -u $LINUX_USERNAME`
-ME_GID=`id -g $LINUX_USERNAME`
+source $HOME/bin/basic-func.sh
+if [[ $? -ne 0 ]]; then
+  echo "sourcing failed"
+  exit 1
+fi
 
-# colors
-COLOR_ERR="\e[31mERR\e[0m"
-COLOR_TRY="\033[33mTRY\033[0m"
-COLOR_OK="\033[34mOK\033[0m "
+network_username="a1548834"
+linux_username=$(whoami)
+var_uid=$(id -u $linux_username)
+var_gid=$(id -g $linux_username)
 
-PASSWORD=$(cat $HOME/Vaults/o2/o2_a1548834_password.txt)
 CREDENTIALS=$HOME/Vaults/o2/o2_a1548834_cifs_credentials.txt
+[[ ! -f "$CREDENTIALS" ]] && fdie "No pass provided, bail out: $CREDENTIALS"
+
 RANDOM_NAME=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 16)
 WRITABLE_CREDENTIALS="/tmp/$RANDOM_NAME"
 
 
-if [[ ! -f "$CREDENTIALS" ]]; then
-    echo -e "$COLOR_ERR: No pass provided, bail out: $CREDENTIALS"
-    exit 1
-fi
-
-
 # select the share to be mounted
 MOUNTFILE=$(ls $HOME/bin/a-write-mounts | fzf --prompt="Vyber mount: ")
-if [[ -z "$MOUNTFILE" ]]; then
-    echo -e "$COLOR_ERR: No mount selected, bail out"
-    exit 1
-fi
+[[ -z "$MOUNTFILE" ]] && fdie "No mount selected, bail out"
+
 
 # source the mount file and set vars
 source $HOME/bin/a-write-mounts/$MOUNTFILE
 
 # copy credentials
-cp $CREDENTIALS $WRITABLE_CREDENTIALS
-chmod 666 $RANDOM_NAME
+cp $CREDENTIALS $WRITABLE_CREDENTIALS || fdie "failed to copy credentials"
+chmod 666 $WRITABLE_CREDENTIALS || fdie "failed to make credentials readable"
 
 MOUNT_POINT=$_MNT_
 SHARE_UNC=$_SRC_
 
 findmnt $MOUNT_POINT >/dev/null 2>&1
 if [ $? -eq 0 ]; then
-    echo -e "$COLOR_OK: directory is already mounted: $MOUNT_POINT"
+    flog "directory is already mounted: $MOUNT_POINT" warning
 else
-    echo -e "$COLOR_TRY: mounting $SHARE_UNC"
+    flog "mounting $SHARE_UNC to $MOUNT_POINT" info
     MM_OPTIONS="credentials=$WRITABLE_CREDENTIALS,"
-    MM_OPTIONS+="uid=$ME_UID,"
-    MM_OPTIONS+="gid=$ME_GID,"
+    MM_OPTIONS+="uid=$var_uid,"
+    MM_OPTIONS+="gid=$var_gid,"
     MM_OPTIONS+="dir_mode=0755,file_mode=0755"
-    MM_OPTIONS+=$_SUFFIX_    
-    echo -e $COLOR_TRY mount -t cifs -o "$MM_OPTIONS" "$SHARE_UNC" "$MOUNT_POINT"
+    MM_OPTIONS+=$_SUFFIX_
+    if [[ ! -d $MOUNT_POINT ]]; then
+        flog "mount point does not exist, creating it"
+        sudo mkdir $MOUNT_POINT
+    fi
     sudo mount -t cifs -o "$MM_OPTIONS" "$SHARE_UNC" "$MOUNT_POINT"
-
-
-    if [ $? -eq 0 ]; then
-        echo -e "$COLOR_OK: mounted as $MOUNT_POINT"        
-    else
-        echo -e "$COLOR_ERR: error ???"
-        echo -e "$COLOR_TRY: ca: https://pam.cz.o2/PasswordVault/v10/Accounts"
-        echo -e "$COLOR_TRY: check credentials: $CREDENTIALS"
+    if [ $? -ne 0 ]; then
+        flog "mount failed" error
+        flog "- ca: https://pam.cz.o2/PasswordVault/v10/Accounts" error
+        flog "- check credentials: $CREDENTIALS" error
     fi
 fi
 
diff --git a/bin/fumount b/bin/fumount
--- a/bin/fumount
+++ b/bin/fumount
@@ -1,24 +1,22 @@
 #!/bin/bash
 
-COLOR_ERR="\e[31mERR\e[0m"
-COLOR_TRY="\033[33mTRY\033[0m"
-COLOR_OK="\033[34mOK\033[0m "
+source $HOME/bin/basic-func.sh
+if [[ $? -ne 0 ]]; then
+  echo "sourcing failed"
+  exit 1
+fi
+
 
 MOUNT_POINT=$(ls /mnt | fzf --prompt="Vyber mount: ")
-if [[ -z "$MOUNT_POINT" ]]; then
-    echo -e "$COLOR_ERR: No mount selected, bail out"
-    exit 1
-fi
+[[ -z "$MOUNT_POINT" ]] && fdie "No mount selected, bail out"
 
 sudo umount "/mnt/$MOUNT_POINT"
 if [ $? -eq 0 ]; then
-    echo -e "$COLOR_OK: Unmounted $MOUNT_POINT successfully"
+    flog "Unmounted $MOUNT_POINT successfully" info
     exit 0
 fi
 
-echo -e "$COLOR_OK: Error unmounting $MOUNT_POINT"
-echo -e "$COLOR_TRY: Find blocking PIDs"
-
+flog "Error unmounting $MOUNT_POINT, find blocking pids" error
 
 # PIDy
 KILL_THESE=$(lsof \
@@ -27,10 +25,7 @@ KILL_THESE=$(lsof \
     | xargs -I{} sh -c 'echo -n "PID: {} CMD: "; tr "\0" " " < /proc/{}/cmdline; echo' \
     | fzf --prompt="Select PID to kill (Shift+Tab to select multiple) ")
 
-if [[ -z "$KILL_THESE" ]]; then
-    echo -e "$COLOR_ERR: bail out"
-    exit 1
-fi
+[[ -z "$KILL_THESE" ]] && fdie "no pids selected, bail out"
 
 # read the selection and kill the PIDs, separator is \0 character
 IFS=$'\0' read -r -a ITEMS <<< "$KILL_THESE"
@@ -39,20 +34,15 @@ for ITEM in "${ITEMS[@]}"; do
     PID=$(echo "$ITEM" | cut -d ' ' -f 2)
     
     if [[ -n "$PID" ]]; then
-        echo -e "$COLOR_TRY: Killing PID $PID"
         kill -9 "$PID"
         if [[ $? -eq 0 ]]; then
-            echo -e "$COLOR_OK: PID $PID killed successfully"
+            flog "PID $PID killed successfully" info
         else 
-            echo -e "$COLOR_ERR: Error killing PID $PID"
+            flog "Error killing PID $PID" warning
         fi
     fi
 done
 
 # try again
-sudo umount "/mnt/$MOUNT_POINT"
-if [ $? -eq 0 ]; then
-    echo -e "$COLOR_OK: Unmounted $MOUNT_POINT successfully"
-    exit 0
-fi
-echo -e "$COLOR_OK: Error unmounting $MOUNT_POINT"
+sudo umount "/mnt/$MOUNT_POINT" || fdie "Error unmounting $MOUNT_POINT" 
+flog "done"
diff --git a/bin/netmount b/bin/netmount
--- a/bin/netmount
+++ b/bin/netmount
@@ -1,100 +1,77 @@
 #!/bin/bash
 
-MM_DEFDIR=$HOME/bin/net-mount-points
-MM_PASSWORD_FILE=$HOME/Vaults/o2/domain-password.txt
+source $HOME/bin/basic-func.sh
+if [[ $? -eq 0 ]]; then
+  flog "Sourcing succeeded"
+else
+  echo "Sourcing failed"
+  exit 1
+fi
 
-# colors
-MM_ERR="\e[31mERR\e[0m"
-MM_TRY="\033[33mTRY\033[0m"
-MM_OK="\033[34mOK\033[0m "
+mount_points_def_dir=$HOME/bin/net-mount-points
+domain_passfile=$HOME/Vaults/o2/domain-password.txt
 
 
-CHOICE=$(echo "mount a git fetch
+what_to_do=$(echo "mount a git fetch
 mount
 jenom vpn" | fzf)
 
-# kontrola existence adresáře s definicemi
-echo -e "$MM_TRY: test mount points config: $MM_DEFDIR"
-if [ ! -d "$MM_DEFDIR" ]; then
-    echo -e "$MM_ERR: Directory does not exist: $MM_DEFDIR <directory>"
-    exit 1
+# sanity check and cryfs
+[[ -d "$mount_points_def_dir" ]] || fdie "Directory does not exist: $mount_points_def_dir"
+if [[ ! -f "$domain_passfile" ]]; then
+    flog "try to read: $domain_passfile" info
+    cryfs $HOME/.local/share/plasma-vault/o2.enc $HOME/Vaults/o2/ || fdie "cryfs failed"
 fi
-echo -e "$MM_OK: mount point config dir exists"
-
-# kontrola existence secrets souboru
-echo -e "$MM_TRY: test secrets file: $MM_PASSWORD_FILE"
-if [ ! -f "$MM_PASSWORD_FILE" ]; then
-    echo -e "$MM_ERR: File does not exist: $MM_PASSWORD_FILE"
-
-    cryfs $HOME/.local/share/plasma-vault/o2.enc $HOME/Vaults/o2/
-fi
-
-echo -e "$MM_TRY: test secrets file: $MM_PASSWORD_FILE"
-if [ ! -f "$MM_PASSWORD_FILE" ]; then
-    echo -e "$MM_ERR: File does not exist: $MM_PASSWORD_FILE"
-    exit 1
-fi
-
+[[ -f "$domain_passfile" ]] || fdie "File does not exist: $domain_passfile"
 
 
 # načti secrets a další
-echo -e "$MM_TRY: read secrets: $MM_PASSWORD_FILE"
-_ME_=`whoami`
-_UID_=`id -u $_ME_`
-_GID_=`id -g $_ME_`
-_PASS_=`cat ~/Vaults/o2/domain-password.txt`
+var_me=$(whoami)
+var_uid=$(id -u $var_me)
+var_gid=$(id -g $var_me)
+var_pass=$(<$HOME/Vaults/o2/domain-password.txt)
+[[ -z $var_pass ]] && fdie "failed to read domain password from $domain_passfile"
 
-if [ -z "$_PASS_" ]; then
-    echo -e "$ERR: read secrets: failed: $MM_PASSWORD_FILE"
-    exit 1
-fi
-echo -e "$MM_OK: secrets read"
+flog "secrets read sucessfully" info
 
 # test napojení na VPN
-IS_O2_CONUP=`nmcli connection show --active | grep extvpn.o2.cz`
-if [ -z "$IS_O2_CONUP" ]; then
-	echo -e "$ERR: connecting to VPN"
-	nmcli connection up extvpn.o2.cz
-else
-	echo -e "IS_O2_CONUP=>$IS_O2_CONUP<"
+is_on_vpn=$(nmcli connection show --active | grep extvpn.o2.cz)
+if [[ -z "$is_on_vpn" ]]; then
+	flog "connecting to VPN" warning
+	nmcli connection up extvpn.o2.cz || fdie "failed to connect"
 fi
 
 
 # proveď mount
 #if [ "${__MOUNT_DRIVES__^^}" = "Y" ]; then 
-if [[ "$CHOICE" =~ "mount" ]]; then
-    for MM_DEFFILE in "$MM_DEFDIR"/*; do
-        echo -e "$MM_TRY: read $MM_DEFFILE"
-        source $MM_DEFFILE
+if [[ "$what_to_do" =~ "mount" ]]; then
+    for mount_point in "$mount_points_def_dir"/*; do
+        flog "read $mount_point" info
+        source $mount_point
 
         if [ -d "$_MNT_" ]; then
             findmnt $_MNT_ >/dev/null 2>&1
             if [ $? -eq 0 ]; then
-                echo -e "$MM_OK: directory is already mounted: $_MNT_"
+                flog "directory is already mounted: $_MNT_" warning
             else
-                echo -e "$MM_TRY: mounting $_SRC_"
+                flog "mounting $_SRC_" info
                 MM_OPTIONS="domain=TO2,username=X0548834,"
-                MM_OPTIONS+="password=$_PASS_,"
-                MM_OPTIONS+="uid=$_UID_,"
-                MM_OPTIONS+="gid=$_GID_,"
+                MM_OPTIONS+="password=$var_pass,"
+                MM_OPTIONS+="uid=$var_uid,"
+                MM_OPTIONS+="gid=$var_gid,"
                 MM_OPTIONS+="dir_mode=0755,file_mode=0755"
                 MM_OPTIONS+=$_SUFFIX_
                 sudo mount -t cifs -o $MM_OPTIONS $_SRC_ $_MNT_
 
-                if [ $? -eq 0 ]; then
-                    echo -e "$MM_OK: mounted"
-                else
-                    echo -e "$MM_ERR: error ???"
+                if [[ $? -gt 0 ]]; then
+                    flog "failed to mount $_SRC_" error
                 fi
             fi
         fi
     done
-else
-    echo ""
-    echo -e "$MM_ERR: přeskakuji mapování disků!"
 fi
 
 # odjeď git fetch
-if [[ "$CHOICE" =~ "git" ]]; then
+if [[ "$what_to_do" =~ "git" ]]; then
     $HOME/bin/git-o2fetch
 fi
diff --git a/bin/netumount b/bin/netumount
--- a/bin/netumount
+++ b/bin/netumount
@@ -1,34 +1,24 @@
 #!/bin/bash
 
-MM_DEFDIR=$HOME/bin/net-mount-points
-MM_PASSWORD_FILE=$HOME/Vaults/o2/domain-password.txt
-
-# colors
-MM_ERR="\e[31mERR\e[0m"
-MM_TRY="\033[33mTRY\033[0m"
-MM_OK="\033[34mOK\033[0m "
-
-
-# kontrola existence adresáře s definicemi
-echo -e "$MM_TRY: test mount points config: $MM_DEFDIR"
-if [ ! -d "$MM_DEFDIR" ]; then
-    echo -e "$MM_ERR: Directory does not exist: $MM_DEFDIR <directory>"
-    exit 1
-fi
-echo -e "$MM_OK"
-
-# kontrola existence secrets souboru
-echo -e "$MM_TRY: test secrets file: $MM_PASSWORD_FILE"
-if [ ! -f "$MM_PASSWORD_FILE" ]; then
-    echo -e "$MM_ERR: File does not exist: $MM_PASSWORD_FILE"
-    exit 1
+source $HOME/bin/basic-func.sh
+if [[ $? -eq 0 ]]; then
+  flog "Sourcing succeeded"
+else
+  echo "Sourcing failed"
+  exit 1
 fi
 
-# načti secrets a další
-_ME_=`whoami`
-_UID_=`id -u $_ME_`
-_GID_=`id -g $_ME_`
 
+mount_points_def_dir=$HOME/bin/net-mount-points
+domain_passfile=$HOME/Vaults/o2/domain-password.txt
+
+# sanity check and cryfs
+[[ -d "$mount_points_def_dir" ]] || fdie "Directory does not exist: $mount_points_def_dir"
+if [[ ! -f "$domain_passfile" ]]; then
+    flog "try to read: $domain_passfile" info
+    cryfs $HOME/.local/share/plasma-vault/o2.enc $HOME/Vaults/o2/ || fdie "cryfs failed"
+fi
+[[ -f "$domain_passfile" ]] || fdie "File does not exist: $domain_passfile"
 
 # co chceme dělat
 CHOICE=$(echo "jenom umount
@@ -36,24 +26,16 @@ umount a disconnect vpn" | fzf)
 
 
 # proveď umount
-for MM_DEFFILE in "$MM_DEFDIR"/*; do
-    echo -e "$MM_TRY: read $MM_DEFFILE"
-    source $MM_DEFFILE
-
-    if [ -d "$_MNT_" ]; then
+for mount_point in "$mount_points_def_dir"/*; do
+    source $mount_point || fdie "failed to source $mount_point"
+    if [[ -d "$_MNT_" ]]; then
         findmnt $_MNT_ >/dev/null 2>&1
-        if [ $? -eq 0 ]; then
-            echo -e "$MM_TRY: unmount: $_MNT_"
+        if [[ $? -eq 0 ]]; then
+            flog "unmount: $_MNT_" warning
             sudo umount -l $_MNT_
-
-            if [ $? -eq 0 ]; then
-                echo -e "$MM_OK: unmounted"
-            else
-                echo -e "$MM_ERR: error ???"
+            if [[ ! $? -eq 0 ]]; then
+                flog "unmount failed"
             fi
-
-        else
-            echo -e "$MM_OK: not mounted: $_SRC_"
         fi
     fi
 done
@@ -61,8 +43,10 @@ done
 if [[ "$CHOICE" =~ "umount a disconnect vpn" ]]; then
     IS_O2_CONUP=$(nmcli connection show --active | grep extvpn.o2.cz)
     if [ -z "$IS_O2_CONUP" ]; then
-        echo -e "$MM_OK: disconnected"
+        flog "disconnected" info
     else
         nmcli connection down extvpn.o2.cz
     fi
 fi
+
+flog "done" info
