mounts

diff --git a/bin/fmount b/bin/fmount
--- a/bin/fmount
+++ b/bin/fmount
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # doc: Interaktivní CIFS mount s automatickým nastavením credentials a práv
 
-[ "$(type -t include)" != 'function' ]&&{ include(){ { [ -z "$_IR" ]&&_IR="$PWD"&&cd "$(dirname "${BASH_SOURCE[0]}")"&&include "$1"&&cd "$_IR"&&unset _IR;}||{ local d="$PWD"&&cd "$(dirname "$PWD/$1")"&&. "$(basename "$1")"&&cd "$d";}||{ echo "Include failed $PWD->$1"&&exit 1;};};}
+[ "$(type -t include)" != 'function' ] && { include() { { [ -z "$_IR" ] && _IR="$PWD" && cd "$(dirname "${BASH_SOURCE[0]}")" && include "$1" && cd "$_IR" && unset _IR; } || { local d="$PWD" && cd "$(dirname "$PWD/$1")" && . "$(basename "$1")" && cd "$d"; } || { echo "Include failed $PWD->$1" && exit 1; }; }; }
 include "lib/user_io.sh"
 include "lib/die.sh"
 
@@ -19,11 +19,9 @@ CREDENTIALS=$HOME/Vaults/o2/o2_a1548834_cifs_credentials.txt
 RANDOM_NAME=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 16)
 WRITABLE_CREDENTIALS="/tmp/$RANDOM_NAME"
 
-
 # select the share to be mounted
 MOUNTFILE=$(ls $HOME/bin/a-write-mounts | fzf --prompt="Vyber mount: ")
 [[ -z "$MOUNTFILE" ]] && fDie "No mount selected, bail out"
-
 
 # source the mount file and set vars
 source $HOME/bin/a-write-mounts/$MOUNTFILE
@@ -40,33 +38,34 @@ MOUNT_POINT=$_MNT_
 SHARE_UNC=$_SRC_
 
 printInfo "testing if the drive is mounted: $MOUNT_POINT"
-findmnt $MOUNT_POINT 
+findmnt $MOUNT_POINT
 is_mounted=$?
 if [ $is_mounted -eq 0 ]; then
-    printSuccess "directory is already mounted: $MOUNT_POINT"
+  printSuccess "directory is already mounted: $MOUNT_POINT"
 else
-    printInfo "mounting $SHARE_UNC to $MOUNT_POINT"
-    MM_OPTIONS="credentials=$WRITABLE_CREDENTIALS,"
-    MM_OPTIONS+="uid=$var_uid,"
-    MM_OPTIONS+="gid=$var_gid,"
-    MM_OPTIONS+="dir_mode=0755,file_mode=0755"
-    MM_OPTIONS+=$_SUFFIX_
-    if [[ ! -d $MOUNT_POINT ]]; then
-        printWarn "mount point does not exist, creating it... you may have to tyupe sudo password"
-        sudo mkdir $MOUNT_POINT
-    fi
-    printInfo "mount options: $MM_OPTIONS"
-    sudo mount -t cifs -o "$MM_OPTIONS" "$SHARE_UNC" "$MOUNT_POINT"
-    if [ $? -ne 0 ]; then
-        printError "mount failed" error
-        printError "- ca: https://pam.cz.o2/PasswordVault/v10/Accounts"
-        printError "- check credentials: $CREDENTIALS" error
-        printError "sudo mount -t cifs -o \"$MM_OPTIONS\" \"$SHARE_UNC\" \"$MOUNT_POINT\""
-        credentials=$(cat $WRITABLE_CREDENTIALS)
-        printError "$credentials"
-    fi
+  printInfo "mounting $SHARE_UNC to $MOUNT_POINT"
+  MM_OPTIONS="credentials=$WRITABLE_CREDENTIALS,"
+  MM_OPTIONS+="uid=$var_uid,"
+  MM_OPTIONS+="gid=$var_gid,"
+  MM_OPTIONS+="dir_mode=0755,file_mode=0755"
+  MM_OPTIONS+=$_SUFFIX_
+  if [[ ! -d $MOUNT_POINT ]]; then
+    printWarn "mount point does not exist, creating it... you may have to tyupe sudo password"
+    sudo mkdir $MOUNT_POINT
+  fi
+  printInfo "mount options: $MM_OPTIONS"
+  sudo mount -t cifs -o "$MM_OPTIONS" "$SHARE_UNC" "$MOUNT_POINT"
+  if [ $? -ne 0 ]; then
+    printError "mount failed" error
+    printError "- ca: https://pam.cz.o2/PasswordVault/v10/Accounts"
+    printError "- check credentials: $CREDENTIALS" error
+    printError "sudo mount -t cifs -o \"$MM_OPTIONS\" \"$SHARE_UNC\" \"$MOUNT_POINT\""
+    credentials=$(cat $WRITABLE_CREDENTIALS)
+    printError "$credentials"
+  fi
 fi
 
 # dismount the vault, remove credentials
 rm $WRITABLE_CREDENTIALS
-$HOME/bin/vault -u
+# $HOME/bin/vault -u
+
diff --git a/bin/fumount b/bin/fumount
--- a/bin/fumount
+++ b/bin/fumount
@@ -1,45 +1,45 @@
 #!/usr/bin/env bash
 # doc: Umount CIFS s automatickým zabíjením blokujících procesů
-[ "$(type -t include)" != 'function' ]&&{ include(){ { [ -z "$_IR" ]&&_IR="$PWD"&&cd "$(dirname "${BASH_SOURCE[0]}")"&&include "$1"&&cd "$_IR"&&unset _IR;}||{ local d="$PWD"&&cd "$(dirname "$PWD/$1")"&&. "$(basename "$1")"&&cd "$d";}||{ echo "Include failed $PWD->$1"&&exit 1;};};}
+[ "$(type -t include)" != 'function' ] && { include() { { [ -z "$_IR" ] && _IR="$PWD" && cd "$(dirname "${BASH_SOURCE[0]}")" && include "$1" && cd "$_IR" && unset _IR; } || { local d="$PWD" && cd "$(dirname "$PWD/$1")" && . "$(basename "$1")" && cd "$d"; } || { echo "Include failed $PWD->$1" && exit 1; }; }; }
 include "lib/user_io.sh"
 include "lib/die.sh"
 
-MOUNT_POINT=$(ls /mnt | fzf --prompt="Vyber mount: ")
+MOUNT_POINT=$(mount | awk '{print $3}' | grep '/mnt' | fzf --prompt="Vyber mount: ")
 [[ -z "$MOUNT_POINT" ]] && fDie "No mount selected, bail out"
 
-sudo umount "/mnt/$MOUNT_POINT"
+sudo umount "$MOUNT_POINT"
 if [ $? -eq 0 ]; then
-    printInfo "Unmounted $MOUNT_POINT successfully"
-    exit 0
+  printInfo "Unmounted $MOUNT_POINT successfully"
+  exit 0
 fi
 
 printError "Error unmounting $MOUNT_POINT, find blocking pids" error
 
 # PIDy
-KILL_THESE=$(lsof \
-    | grep '/mnt/ntbimetadata401-w-f' \
-    | awk '{print $2}' \
-    | xargs -I{} sh -c 'echo -n "PID: {} CMD: "; tr "\0" " " < /proc/{}/cmdline; echo' \
-    | fzf --prompt="Select PID to kill (Shift+Tab to select multiple) ")
+KILL_THESE=$(lsof |
+  grep "$MOUNT_POINT" |
+  awk '{print $2}' |
+  xargs -I{} sh -c 'echo -n "PID: {} CMD: "; tr "\0" " " < /proc/{}/cmdline; echo' |
+  fzf --prompt="Select PID to kill (Shift+Tab to select multiple) ")
 
 [[ -z "$KILL_THESE" ]] && fDie "no pids selected, bail out"
 
 # read the selection and kill the PIDs, separator is \0 character
-IFS=$'\0' read -r -a ITEMS <<< "$KILL_THESE"
+IFS=$'\0' read -r -a ITEMS <<<"$KILL_THESE"
 for ITEM in "${ITEMS[@]}"; do
-    # use cut to extract the PID from the selection
-    PID=$(echo "$ITEM" | cut -d ' ' -f 2)
-    
-    if [[ -n "$PID" ]]; then
-        kill -9 "$PID"
-        if [[ $? -eq 0 ]]; then
-            printSuccess "PID $PID killed successfully"
-        else 
-            printError "Error killing PID $PID"
-        fi
+  # use cut to extract the PID from the selection
+  PID=$(echo "$ITEM" | cut -d ' ' -f 2)
+
+  if [[ -n "$PID" ]]; then
+    kill -9 "$PID"
+    if [[ $? -eq 0 ]]; then
+      printSuccess "PID $PID killed successfully"
+    else
+      printError "Error killing PID $PID"
     fi
+  fi
 done
 
 # try again
-sudo umount "/mnt/$MOUNT_POINT" || fDie "Error unmounting $MOUNT_POINT" 
+sudo umount "/mnt/$MOUNT_POINT" || fDie "Error unmounting $MOUNT_POINT"
 printSuccess "done"
diff --git a/bin/netumount b/bin/netumount
--- a/bin/netumount
+++ b/bin/netumount
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # doc: Odpojí síťové disky a volitelně i VPN spojení
-[ "$(type -t include)" != 'function' ]&&{ include(){ { [ -z "$_IR" ]&&_IR="$PWD"&&cd "$(dirname "${BASH_SOURCE[0]}")"&&include "$1"&&cd "$_IR"&&unset _IR;}||{ local d="$PWD"&&cd "$(dirname "$PWD/$1")"&&. "$(basename "$1")"&&cd "$d";}||{ echo "Include failed $PWD->$1"&&exit 1;};};}
+[ "$(type -t include)" != 'function' ] && { include() { { [ -z "$_IR" ] && _IR="$PWD" && cd "$(dirname "${BASH_SOURCE[0]}")" && include "$1" && cd "$_IR" && unset _IR; } || { local d="$PWD" && cd "$(dirname "$PWD/$1")" && . "$(basename "$1")" && cd "$d"; } || { echo "Include failed $PWD->$1" && exit 1; }; }; }
 include "lib/user_io.sh"
 include "lib/die.sh"
 
@@ -8,61 +8,58 @@ mount_points_def_dir=$HOME/bin/net-mount-points
 vpn_client="/opt/cisco/anyconnect/bin/vpn"
 vpn_client_ui="vpnui"
 
+for mount_point in "${mounted_dirs[*]}"; do
+  printInfo "mounted: $mount_point"
+done
 
 # co chceme dělat
 CHOICE=$(echo "jenom umount
 umount a disconnect vpn" | fzf)
 
-
 # proveď umount
-for mount_point in "$mount_points_def_dir"/*; do
-    source $mount_point || fDie "failed to source $mount_point"
-    if [[ -d "$_MNT_" ]]; then
-        findmnt $_MNT_ >/dev/null 2>&1
-        if [[ $? -eq 0 ]]; then
-            printWarn "unmount: $_MNT_"
-            sudo umount -l $_MNT_
-            if [[ ! $? -eq 0 ]]; then
-                printError "unmount failed"
-            fi
-        fi
+mount | awk '{ print $3 }' | grep '/mnt' | while IFS= read -r mnt; do
+  printInfo "Got mountpoint: $mnt"
+  if [[ $? -eq 0 ]]; then
+    printWarn "unmount: $mnt"
+    sudo umount -l $mnt
+    if [[ ! $? -eq 0 ]]; then
+      printError "unmount failed"
     fi
+  fi
 done
 
+if [[ "$CHOICE" =~ "umount a disconnect vpn" ]]; then
+  # CISCO # is_on_vpn=$(ps aux | grep vpnui | grep -v grep | awk ' { print $2 }')
+  # CISCO # if [[ ! -z "$is_on_vpn" ]]; then
+  # CISCO #     flog "disconnecting VPN" warning
+  # CISCO #     $vpn_client disconnect extvpn.o2.cz
+  # CISCO #     killall $vpn_client_ui
+  # CISCO #     if [[ -d "$HOME/.cisco" ]]; then
+  # CISCO #         flog "removing dir $HOME/.cisco" warning
+  # CISCO #         rm -rf "$HOME/.cisco"
+  # CISCO #     fi
+  # CISCO # else
+  # CISCO #     flog "VPN is not connected" info
+  # CISCO # fi
+  IS_O2_CONUP=$(nmcli connection show --active | grep extvpn.o2.cz)
+  if [ -z "$IS_O2_CONUP" ]; then
+    printInfo "disconnected"
+  else
+    nmcli connection down extvpn.o2.cz
+    $HOME/bin/set-proxy-off
 
-
-if [[ "$CHOICE" =~ "umount a disconnect vpn" ]]; then    
-    # CISCO # is_on_vpn=$(ps aux | grep vpnui | grep -v grep | awk ' { print $2 }')
-    # CISCO # if [[ ! -z "$is_on_vpn" ]]; then
-    # CISCO #     flog "disconnecting VPN" warning
-    # CISCO #     $vpn_client disconnect extvpn.o2.cz
-    # CISCO #     killall $vpn_client_ui
-    # CISCO #     if [[ -d "$HOME/.cisco" ]]; then
-    # CISCO #         flog "removing dir $HOME/.cisco" warning
-    # CISCO #         rm -rf "$HOME/.cisco"
-    # CISCO #     fi
-    # CISCO # else
-    # CISCO #     flog "VPN is not connected" info
-    # CISCO # fi    
-    IS_O2_CONUP=$(nmcli connection show --active | grep extvpn.o2.cz)
-    if [ -z "$IS_O2_CONUP" ]; then
-        printInfo "disconnected"
+    # set proxy discovery
+    # in the file, find the lie ProxyType=\d and set it to ProxyType=3
+    # 0 - no proxy
+    # 3 - autodetect
+    kioslaverc_file="$HOME/.config/kioslaverc"
+    sed -i 's/ProxyType=[0-9]/ProxyType=0/' "$kioslaverc_file"
+    if [[ $? -eq 0 ]]; then
+      printSuccess "kde: $HOME/.config/kioslaverc: set ProxyType=0 (no proxy)"
     else
-        nmcli connection down extvpn.o2.cz
-        $HOME/bin/set-proxy-off
-        
-        # set proxy discovery
-        # in the file, find the lie ProxyType=\d and set it to ProxyType=3
-        # 0 - no proxy
-        # 3 - autodetect
-        kioslaverc_file="$HOME/.config/kioslaverc"
-        sed -i 's/ProxyType=[0-9]/ProxyType=0/' "$kioslaverc_file"
-        if [[ $? -eq 0 ]]; then
-            printSuccess "kde: $HOME/.config/kioslaverc: set ProxyType=0 (no proxy)"
-        else
-            printError "ERR: kde: $HOME/.config/kioslaverc: set ProxyType=0 (no proxy)"
-        fi
+      printError "ERR: kde: $HOME/.config/kioslaverc: set ProxyType=0 (no proxy)"
     fi
+  fi
 fi
 
 $HOME/bin/vault -u
